name: Build and Release OPKG

on:
  push:
    tags:
      - 'v*' # Срабатывает автоматически, когда ты создаешь тег версии (например, v1.0.11)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.13' # Жестко фиксируем стабильную версию рантайма

      - name: Build MIPSLE Binary
        run: |
          mkdir -p build
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o build/dns-wan-transport_mipsle cmd/daemon/main.go

      - name: Build OPKG Package
        run: |
          chmod +x deployment/opkg/build_package.sh
          ./deployment/opkg/build_package.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/dns-wan-transport_*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
